name: lms_mobile_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  dio: ^5.7.0
  socket_io_client: ^2.0.3+1
  flutter_webrtc: ^0.12.12+hotfix.1
  shared_preferences: ^2.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  file_picker: ^8.3.7
  path_provider: ^2.1.4
  permission_handler: ^11.4.0
  open_filex: ^4.5.0
  overlay_support: ^2.1.0
  easy_localization: ^3.0.5
  intl: ^0.20.2
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  pdfx: ^2.6.0
  video_player: ^2.9.1
  flutter_local_notifications: ^17.2.3
  shimmer: ^3.0.0
  connectivity_plus: ^6.0.5
  flutter_secure_storage: ^9.2.2
  image_picker: ^1.2.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/en.json
    - assets/i18n/vi.json
